### PR TITLE
Strong-name the assemblies

### LINKED ISSUE #8: Assembly does not have a strong name
Without a strong name, a strong-named project will get this error.

> CS8002: Referenced assembly 'PackageUrl, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.

You just need to generate an snk at the root of the repo (let's say `StrongName.snk`), and add this to `Directory.Build.props`:
```xml
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>$(MSBuildThisFileDirectory)StrongName.snk</AssemblyOriginatorKeyFile>
```

### PR DESCRIPTION
**Pull request by dfederm**
Fixes #8 

I generated the snk file simply by running `sn -k StrongName.snk`.

I also added a pretty basic `Directory.Build.props` and `Directory.Build.rsp`

### CODE REVIEW

**Comment by dfederm** [comment]
CC @am11 @ThomasPiskol @JamieMagee

**Comment by dfederm** [comment]
@ThomasPiskol since you have maintainer access now (yay!), mind taking a look? My hope is to get this merged, pushed to NuGet.org, and integrated downstream by EOW :)

**Review by ThomasPiskol — APPROVED** [review]
Looks good from my point of view. 👍

**Comment by ThomasPiskol** [comment]
> My hope is to get this merged, pushed to NuGet.org, and integrated downstream by EOW :)

I'll integrate the changes in my PR, so let's see if we can let your wish come true 🙂

**Pull request merged**
