### PR TITLE
Add [JsonConstructor] to the PackageURL constructor

### PR DESCRIPTION
**Pull request by jpinz**
Added the correct annotations to the PackageURL constructor to use with JSON Deserialization. And a test to assert that the serialization and de-serialization works correctly.

### CODE REVIEW

**Comment by jpinz** [comment]
@am11 Hope this makes more sense. The tests probably aren't all that necessary so I can remove them if you'd like. It's just the [JsonConstructor] that needed to be added to support JSON deserialization.

**Comment by am11** [comment]
@jpinz, what is the use-case? I'd expect user would typically have data like:

```json
{ "title": "payload1", "purl": "pkg:npm/foo@1.2.3" }
```

that serializes and deserielizes To/From string to PackageURL object just fine when using System.Text.Json; as opposed to individual properties of purl:

```json
{ "title": "payload1", "purl": "{\"Scheme\":\"pkg\",\"Type\":\"npm\",\"Namespace\":null,\"Name\":\"foo\", \"Version\":\"1.2.3\",\"Qualifiers\":null,\"Subpath\":null}"}
```

which is PR aims to support. Did I miss something?

**Comment by jpinz** [comment]
> @jpinz, what is the use-case? I'd expect user would typically have data like:
> 
> ```json
> { "title": "payload1", "purl": "pkg:npm/foo@1.2.3" }
> ```
> 
> that serializes and deserielizes to/from string to PackageURL object just fine when using System.Text.Json; as opposed to individual properties of purl:
> 
> ```json
> { "title": "payload1", "purl": "{\"Scheme\":\"pkg\",\"Type\":\"npm\",\"Namespace\":null,\"Name\":\"foo\", \"Version\":\"1.2.3\",\"Qualifiers\":null,\"Subpath\":null}"}
> ```
> 
> which is PR aims to support. Did I miss something?

You are completely correct, it is possible to create a custom converter to do the json serializing and deserializing using the PackageURL parse method and toString method. This PR would support the latter where if the PackageURL was stored in a more key/value json structure whether its for easy parsing in a database or whatever, the [JsonConstructor] specifies the constructur to use for JSON deserializing which is needed because there are 3 constructors for PackageURL.

**Comment by am11** [comment]
> if the PackageURL was stored in a more key/value json structure whether its for easy parsing in a database

1. Supported:
```json
{ "title": "payload1", "purl": "pkg:npm/foo@1.2.3" }
```

2. Unsupported:
```json
{ "title": "payload1", "purl": "{\"Scheme\":\"pkg\",\"Type\":\"npm\",\"Namespace\":null,\"Name\":\"foo\", \"Version\":\"1.2.3\",\"Qualifiers\":null,\"Subpath\":null}"}
```

3. also unsupported:
```json
{
  "title": "payload1",
  "purl":
  {
    "Scheme": "pkg",
    "Type ": "npm",
    "Namespace": null,
    "Name": "foo", 
    "Version": "1.2.3",
    "Qualifiers": null,
    "Subpath": null
  }
}
```

If I understand it correctly, this PR is only adding support for `2.`, right?

My concern is:

* how are you obtaining data represented in `2.` in the first place? is it some interop scenario (e.g. JS library is producing that on client, which server will deserialize)?
* how common do you think is this use-case when user would need such nested serialization? (i.e. I imagine most folks will use `1.` and not `2.` and `3.`?)
* in the same spirit, what about support for `3.`?

If this is not common enough, does STJ's custom converter work for you? Going down this path, when someone will be using other library like Json.NET, or other serialization technology like YAML, flackbuffers etc. they will need separate annotations.

**Comment by jpinz** [comment]
> If this is not common enough, does STJ's custom converter work for you? Going down this path, when someone will be using other library like Json.NET, or other serialization technology like YAML, flatbuffers etc. they will need separate annotations.

Thank you for working through this with me, much appreciated. I have made a custom PackageUrlJsonConverter in our project that serializes the object to the package url string spec, and then deserializes it back into the correct PackageUrl object which appears to be working great!
So yeah, I now think that adding the JsonConstructor might complicate things more than necessary, I will close this PR.

**Pull request closed without merging**
