### PR TITLE
Use correct syntax for environment variable

### PR DESCRIPTION
**Pull request by ThomasPiskol**
Fixes the upload issue due to missing API key because of wrong syntax.

### CODE REVIEW

**Comment by ThomasPiskol** [comment]
@am11 That should fix the issue with token [which you have faced](https://github.com/package-url/packageurl-dotnet/runs/5345819413#step:6:39).

**Review by am11 — APPROVED** [review]
Thank you! 🎉

**Comment by am11** [comment]
Ah, it failed again: https://github.com/package-url/packageurl-dotnet/runs/5346177918
Perhaps the key which was added in repository secrets is incorrect?

**Comment by ThomasPiskol** [comment]
@am11 I've created an issue: #12 let's continue the discussion there.

**Pull request merged**
